### ISSUE TITLE
折腾了半天 原来局域网要改成电脑ip才能连上

### ISSUE THREAD

**Issue by chandou-code** [Ljzd-PRO/PyDGLab-WS#35]
async def main():
    async with DGLabWSServer("0.0.0.0", 5678, 60) as server:
        client = server.new_local_client()

        url = client.get_qrcode("ws://192.168.1.198:5678")
        print("请用 DG-Lab App 扫描二维码以连接")

        # 将二维码保存为图片
        save_qrcode_to_image(url, "qrcode.png")

192.168.1.198改成电脑IP

**Comment by Ljzd-PRO** [comment]
是的，可能这里没有说明的很详细，这个是因为App扫描的二维码里包含了Websocket URL，需要是手机能够连接的地址
