### ISSUE TITLE
help wanted 我如何在dg循环外增加波形

### ISSUE THREAD

**Issue by killjsj** [Ljzd-PRO/PyDGLab-WS#36]
![image](https://github.com/user-attachments/assets/db324f49-26a7-4298-9793-3b4c5827dd76)

**Comment by killjsj** [comment]
他会进入分支but执行后没用（im python Noob)

**Comment by Ljzd-PRO** [comment]
可以确保绑定后才添加波形吗

**Comment by killjsj** [comment]
可以
![image](https://github.com/user-attachments/assets/fb0044e1-ce3c-4e90-9ed3-31dd5206cdaf)

**Comment by Ljzd-PRO** [comment]
设置强度在那边有效果吗，如果有效果的话可能是波形数据的问题

**Comment by killjsj** [comment]
。。。 波形是
![image](https://github.com/user-attachments/assets/98c5bdcb-5c84-449f-b660-554f32fd24a7)
（hp至少大于0）

**Comment by killjsj** [comment]
.。。
知道有一个问题在哪了```elif hp < 0:
                    pulse = calc_pulse(-hp)
                    await client.add_pulses(sent2,*(pulse["add"]))```

**Comment by Ljzd-PRO** [comment]
DGLAB App的日志功能也可以开启，会在App里显示收到的消息之类的，比较方便排查问题。

**Comment by killjsj** [comment]
ok
明天试试

**Comment by killjsj** [comment]
e...
![Screenshot_2024-11-01-18-58-24-489_com bjsm dunge](https://github.com/user-attachments/assets/ce45117c-8ed9-4d8b-b5eb-883bbb031f1a)

**Comment by Ljzd-PRO** [comment]
看起来有收到，那可能是波形数据的问题？
https://github.com/Ljzd-PRO/PyDGLab-WS/blob/master/examples/add_pulses.py
可以用这里的波形数据复制过去试试，排查问题

**Comment by killjsj** [comment]
e
确认了 波形问题
thx

**Comment by killjsj** [comment]
对了问一下 [((10, 6, 3, 1), (0, 1, 1, 1)), ((10, 6, 3, 1), (0, 1, 1, 1)), ((10, 6, 3, 1), (0, 1, 1, 1))]
可以用吗

**Comment by Ljzd-PRO** [comment]
最近没怎么关注波形和协议之类的😂具体波形数据有什么要求已经忘了。只是只要数据格式符合
```python3
List[
    Tuple[
        Tuple[int, int, int, int],
        Tuple[int, int, int, int]
    ]
]
```
WebSocket 消息就可以发出去
